AWSTemplateFormatVersion: 2010-09-09
Description: >-
  WHC-Sites
Transform:
- AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: WHC-Sites

  getSitesByLanguage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-sites-by-lang.getSitesByLanguageHandler
      Runtime: nodejs20.x
      Architectures:
      - arm64
      MemorySize: 128
      Timeout: 100
      Description: 
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/countries
            Method: GET
            Auth:
              ApiKeyRequired: true

  getSitesSummaryByCountry:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-sites-by-country.getSitesSummaryByCountryHandler
      Runtime: nodejs20.x
      Architectures:
      - arm64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/countries/{country_name}/summary
            Method: GET
            Auth:
              ApiKeyRequired: true

  ApiGatewayApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: WHC-Sites-ApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: prod

  ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: WHC-Sites-Usa gePlan
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: prod
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  ApiGatewayUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiGatewayApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGatewayUsagePlan

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON